use regex::Regex;
use serde::Serialize;
use std::path::{Path, PathBuf};
use tauri::{AppHandle, Manager};
use tokio::fs;
use tokio::sync::Mutex;

pub const MAX_BACKUPS: usize = 20;
pub const MAX_BACKUP_BYTES: usize = 10 * 1024 * 1024;
const PRUNE_EVERY_N_WRITES: u32 = 5;

pub struct BackupState {
    pub writes_since_prune: Mutex<u32>,
}

impl Default for BackupState {
    fn default() -> Self {
        Self { writes_since_prune: Mutex::new(0) }
    }
}

#[derive(Serialize)]
pub struct WriteResult {
    pub ok: bool,
    pub error: Option<String>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BackupInfo {
    pub name: String,
    pub timestamp: String,
    pub size_bytes: u64,
}

#[derive(Serialize)]
pub struct ListResult {
    pub ok: bool,
    pub backups: Option<Vec<BackupInfo>>,
    pub error: Option<String>,
}

#[derive(Serialize)]
pub struct ReadResult {
    pub ok: bool,
    pub content: Option<String>,
    pub error: Option<String>,
}

// Filenames are always generated by write_backup_file (backup_<iso-with-dashes>.json),
// so this pattern doubles as a path-traversal guard on list/read — it rejects
// anything containing "/" or "..".
pub fn is_valid_backup_filename(name: &str) -> bool {
    let re = Regex::new(r"^backup_[0-9TZ.\-]+\.json$").expect("valid regex");
    re.is_match(name)
}

fn timestamp_for_filename() -> String {
    chrono::Utc::now()
        .to_rfc3339_opts(chrono::SecondsFormat::Millis, true)
        .replace([':', '.'], "-")
}

fn backups_dir(app: &AppHandle) -> Result<PathBuf, String> {
    app.path()
        .app_data_dir()
        .map(|dir| dir.join("backups"))
        .map_err(|e| e.to_string())
}

pub async fn prune_old_backups(dir: &Path) -> std::io::Result<()> {
    let mut entries = match fs::read_dir(dir).await {
        Ok(e) => e,
        Err(_) => return Ok(()),
    };
    let mut backup_files = Vec::new();
    while let Some(entry) = entries.next_entry().await? {
        let name = entry.file_name().to_string_lossy().to_string();
        if name.starts_with("backup_") && name.ends_with(".json") {
            backup_files.push(name);
        }
    }
    backup_files.sort();
    let excess = backup_files.len().saturating_sub(MAX_BACKUPS);
    for name in &backup_files[..excess] {
        let _ = fs::remove_file(dir.join(name)).await;
    }
    Ok(())
}

pub async fn write_backup_file(
    dir: &Path,
    json: &str,
    writes_since_prune: &mut u32,
) -> std::io::Result<()> {
    fs::create_dir_all(dir).await?;
    let filename = format!("backup_{}.json", timestamp_for_filename());
    fs::write(dir.join(filename), json).await?;

    *writes_since_prune += 1;
    if *writes_since_prune >= PRUNE_EVERY_N_WRITES {
        *writes_since_prune = 0;
        prune_old_backups(dir).await?;
    }
    Ok(())
}

pub async fn list_backup_files(dir: &Path) -> std::io::Result<Vec<BackupInfo>> {
    let mut entries = match fs::read_dir(dir).await {
        Ok(e) => e,
        Err(_) => return Ok(Vec::new()),
    };
    let mut backups = Vec::new();
    while let Some(entry) = entries.next_entry().await? {
        let name = entry.file_name().to_string_lossy().to_string();
        if !is_valid_backup_filename(&name) {
            continue;
        }
        let metadata = entry.metadata().await?;
        let modified: chrono::DateTime<chrono::Utc> = metadata.modified()?.into();
        backups.push(BackupInfo {
            name,
            timestamp: modified.to_rfc3339(),
            size_bytes: metadata.len(),
        });
    }
    backups.sort_by(|a, b| b.timestamp.cmp(&a.timestamp));
    Ok(backups)
}

pub async fn read_backup_file(dir: &Path, name: &str) -> Result<String, String> {
    if !is_valid_backup_filename(name) {
        return Err("Invalid backup filename".to_string());
    }
    fs::read_to_string(dir.join(name)).await.map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn backup_write(
    app: AppHandle,
    state: tauri::State<'_, BackupState>,
    json: String,
) -> Result<WriteResult, ()> {
    if json.is_empty() || json.len() > MAX_BACKUP_BYTES {
        return Ok(WriteResult { ok: false, error: Some("Invalid backup payload".to_string()) });
    }
    let dir = match backups_dir(&app) {
        Ok(d) => d,
        Err(e) => return Ok(WriteResult { ok: false, error: Some(e) }),
    };
    let mut writes = state.writes_since_prune.lock().await;
    match write_backup_file(&dir, &json, &mut writes).await {
        Ok(()) => Ok(WriteResult { ok: true, error: None }),
        Err(e) => Ok(WriteResult { ok: false, error: Some(e.to_string()) }),
    }
}

#[tauri::command]
pub async fn backup_list(app: AppHandle) -> Result<ListResult, ()> {
    let dir = match backups_dir(&app) {
        Ok(d) => d,
        Err(e) => return Ok(ListResult { ok: false, backups: None, error: Some(e) }),
    };
    match list_backup_files(&dir).await {
        Ok(backups) => Ok(ListResult { ok: true, backups: Some(backups), error: None }),
        Err(e) => Ok(ListResult { ok: false, backups: None, error: Some(e.to_string()) }),
    }
}

#[tauri::command]
pub async fn backup_read(app: AppHandle, name: String) -> Result<ReadResult, ()> {
    let dir = match backups_dir(&app) {
        Ok(d) => d,
        Err(e) => return Ok(ReadResult { ok: false, content: None, error: Some(e) }),
    };
    match read_backup_file(&dir, &name).await {
        Ok(content) => Ok(ReadResult { ok: true, content: Some(content), error: None }),
        Err(e) => Ok(ReadResult { ok: false, content: None, error: Some(e) }),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn accepts_generated_filename_pattern() {
        assert!(is_valid_backup_filename("backup_2026-07-23T10-15-00-000Z.json"));
    }

    #[test]
    fn rejects_path_traversal_attempts() {
        assert!(!is_valid_backup_filename("../../etc/passwd"));
        assert!(!is_valid_backup_filename("backup_../evil.json"));
        assert!(!is_valid_backup_filename("not-a-backup.json"));
    }

    #[tokio::test]
    async fn write_creates_a_file_readable_back() {
        let dir = tempfile::tempdir().unwrap();
        let mut writes = 0u32;
        write_backup_file(dir.path(), "{\"foo\":1}", &mut writes).await.unwrap();

        let files: Vec<_> = list_backup_files(dir.path()).await.unwrap();
        assert_eq!(files.len(), 1);
        let content = read_backup_file(dir.path(), &files[0].name).await.unwrap();
        assert_eq!(content, "{\"foo\":1}");
    }

    #[tokio::test]
    async fn prunes_only_on_every_fifth_write() {
        let dir = tempfile::tempdir().unwrap();
        let mut writes = 0u32;
        for _ in 0..4 {
            write_backup_file(dir.path(), "{}", &mut writes).await.unwrap();
        }
        assert_eq!(writes, 4);

        write_backup_file(dir.path(), "{}", &mut writes).await.unwrap();
        assert_eq!(writes, 0, "counter resets after the 5th write triggers a prune");
    }

    #[tokio::test]
    async fn read_rejects_invalid_filename_without_touching_disk() {
        let dir = tempfile::tempdir().unwrap();
        let result = read_backup_file(dir.path(), "../../etc/passwd").await;
        assert_eq!(result.unwrap_err(), "Invalid backup filename");
    }

    #[tokio::test]
    async fn list_ignores_non_backup_files() {
        let dir = tempfile::tempdir().unwrap();
        tokio::fs::write(dir.path().join("random.txt"), "hi").await.unwrap();
        let mut writes = 0u32;
        write_backup_file(dir.path(), "{}", &mut writes).await.unwrap();

        let files = list_backup_files(dir.path()).await.unwrap();
        assert_eq!(files.len(), 1);
    }
}
